"""Generate maploc's ground-truth TOML from the MuJoCo apartment scene.

maploc's `evaluate` bench wants a truth file of wall segments, a boot pose and
a kidnap pose, in centimetres and degrees. On hardware you produce that with a
tape measure, and the header of `room_lab.toml` warns that every reported error
inherits any error in the boot pose. In the twin the scene XML *is* the truth,
exactly, and the boot pose is whatever the keyframe says -- so the residual the
bench reports is maploc's, not the ruler's.

One thing this does that a walls-only file would get wrong: `kinematics::tof`
rejects beams that would hit the FLOOR and projects everything else into 2-D,
with no upper height gate. So a fridge, a wardrobe and a coat rack are all
"wall" as far as the map is concerned. Scoring a furnished flat against its
walls alone charges maploc for seeing the furniture that is really there. This
emits the footprint of every collision box that intersects the sensor's height
band, which is what the map can actually contain.

    python3 make_truth.py [--band LO HI] [--walls-only] > apartment.toml
"""
from __future__ import annotations

import argparse
import xml.etree.ElementTree as ET
from pathlib import Path

SCENE = Path("/Users/schade/Pollen/microduck_rl/src/mjlab_microduck/robot/"
             "microduck/apartment.xml")

p = argparse.ArgumentParser()
p.add_argument("--band", nargs=2, type=float, default=[0.02, 0.60],
               metavar=("LO", "HI"),
               help="height band in metres a standing duck's ToF can return")
p.add_argument("--walls-only", action="store_true",
               help="only geoms named wall_*/w[A-Z]* -- the unfurnished view")
p.add_argument("--start", nargs=3, type=float, default=[0.0, 0.0, 0.0],
               metavar=("X_CM", "Y_CM", "YAW_DEG"))
p.add_argument("--kidnap", nargs=3, type=float, default=[200.0, -200.0, 180.0],
               metavar=("X_CM", "Y_CM", "YAW_DEG"))
args = p.parse_args()

LO, HI = args.band
root = ET.parse(SCENE).getroot()

segs: list[tuple[list[float], str]] = []
skipped: list[str] = []

for geom in root.iter("geom"):
    if geom.get("type") != "box":
        continue
    name = geom.get("name", "?")
    # Visual-only overlays (rugs, floor tints) carry no collision and no
    # returns. contype/conaffinity both 0 means the sensor cannot see it.
    if geom.get("contype") == "0" and geom.get("conaffinity") == "0":
        continue
    pos = [float(v) for v in (geom.get("pos") or "0 0 0").split()]
    half = [float(v) for v in geom.get("size").split()]
    if len(half) < 3 or len(pos) < 3:
        continue
    z0, z1 = pos[2] - half[2], pos[2] + half[2]
    if z1 <= LO or z0 >= HI:          # floor tiles, stairs, ceilings
        skipped.append(f"{name} (z {z0:.2f}..{z1:.2f})")
        continue
    if args.walls_only and not (name.startswith("wall_") or
                                (len(name) > 1 and name[0] == "w"
                                 and name[1].isupper())):
        continue
    x0, x1 = (pos[0] - half[0]) * 100, (pos[0] + half[0]) * 100
    y0, y1 = (pos[1] - half[1]) * 100, (pos[1] + half[1]) * 100
    # The footprint's four sides. A wall's two long sides are its real
    # surfaces; using the centerline instead would bias every wall by half
    # its 12 cm thickness.
    for a, b, side in (([x0, y0, x1, y0], None, "S"),
                       ([x1, y0, x1, y1], None, "E"),
                       ([x1, y1, x0, y1], None, "N"),
                       ([x0, y1, x0, y0], None, "W")):
        segs.append((a, f"{name} {side}"))

print("# Ground truth for the MuJoCo apartment, generated by make_truth.py.")
print("# Units: CENTIMETRES and DEGREES. Room frame == MuJoCo world frame.")
print(f"# Height band {LO:.2f}..{HI:.2f} m"
      + (" (walls only)" if args.walls_only else " (walls + furniture)"))
print(f"# {len(segs)} segments from {len(segs) // 4} boxes.")
print()
print("walls = [")
for seg, why in segs:
    nums = ", ".join(f"{v:.1f}" for v in seg)
    print(f"    [{nums}],  # {why}")
print("]")
print()
print("# The keyframe boot pose. In the twin this is exact -- MuJoCo reports")
print("# trunk (0,0) and an identity quaternion -- so unlike the lab room,")
print("# no measurement error is baked into the anchor.")
print(f"start = [{args.start[0]}, {args.start[1]}, {args.start[2]}]")
print(f"kidnap = [{args.kidnap[0]}, {args.kidnap[1]}, {args.kidnap[2]}]")
print()
print(f"# excluded, outside the band: {', '.join(skipped) or 'none'}")
